[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'yield-utils/=lib/yield-utils-v2/contracts/',
    'chainlink/=lib/chainlink/contracts/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config